name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
jobs:
  full-test:
    container: cuaesd/aesd-autotest:assignment4-buildroot
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.Buildroot_Submodule_SSH_PRIVATE_KEY }}

      - name: Ensure full-test.sh is executable
        run: chmod +x ./full-test.sh

      - name: Verify Submodule Initialization
        run: |
          git submodule update --init --recursive
          ls -alh
          ls -alh base_external/
          ls -alh base_external/package/
          ls -alh base_external/package/aesd-assignments/

      - name: Run full test
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: ./full-test.sh

      - name: Cleanup
        if: always()
        run: ssh-add -D

